openapi: 3.0.2
info:
  title: API for Simply Appointments
  description: An Appointment Management System
  version: 1.0.0
servers:
  - url: http://api.simplyappointments.com/v1
  
paths:
    /user:
      post:
        description: Create user
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        responses:
          '201':
            description: User created
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'